### ISSUE TITLE
Update Bulma version to include fix that was preventing compilation on some node versions

### ISSUE THREAD

**Issue by crodriguez1a** [open-tux/ember-bulma#16]

**Comment by Swizz** [comment]
This is related to node-sass through ember-cli-sass issues

I will try a fix thanks to : [ember-cli-sass#choosing-the-version-of-node-sass](https://github.com/aexmachina/ember-cli-sass#choosing-the-version-of-node-sass)


Related :
https://github.com/aexmachina/ember-cli-sass/issues/117
https://github.com/aexmachina/broccoli-sass-source-maps/issues/19
https://github.com/sass/libsass/issues/2017

**Comment by Swizz** [comment]
Seem fixed by https://github.com/sass/libsass/pull/2032

**Comment by crodriguez1a** [comment]
@Swizz Bulma itself is tracking this issue as it relates to some syntactic issue with header.sass. 

https://github.com/jgthms/bulma/issues/191

I was able to get around this by manually installing node-sass 3.2x at broccoli-sass-sourcemaps. I'm not sure exactly how the two coincide but they do seem related.

**Comment by crodriguez1a** [comment]
This issue seems to be the direct result of the node sass version. Closing.
