### ISSUE TITLE
Compile error with button.sass

### ISSUE THREAD

**Issue by crodriguez1a** [open-tux/ember-bulma#20]
Build is currently failing. This is a bulma issue with version 0.0.26
Error: argument `$color` of `darken($color, $amount)` must be a color

**Comment by crodriguez1a** [comment]
Some leads:
https://github.com/sass/libsass/issues/151

**Comment by crodriguez1a** [comment]
This issue was unrelated to the libass issue. This was due to passing a string as color variable:

`$white: white; //no good`
`$white: #fff; //Ok`

**Comment by woodgates** [comment]
Im having the same problem with this compile
@import "node_modules/bulma/sass/utilities/variables";

@import "node_modules/bulma/bulma";

**Comment by crodriguez1a** [comment]
@woodgates Hm, could be a node versus bower thing. You mind opening a new issue describing your experience with this?

Cc/ @alex-DiLiberto
