### ISSUE TITLE
Very serious grammar change

### ISSUE THREAD

**Issue by adepatie** [open-tux/ember-bulma#26]
I don't mean to damage any mutual love affair you may have with Jeremy Thomas, but when I first read the description I was confused for a second as to who Jeremy Thomas was and whether he was a part of TUX. I think getting rid of his name in the description and letting people see who he is by way of Bulma is more concise.

But if his name has to stay it could also be:

"Ember Bulma is an ember addon for Bulma (by Jeremy Thomas)"

or for more detail

"Ember Bulma is a collection of Ember components and services for Bulma, a modern CSS framework by Jeremy Thomas"

Ok back to work

**Comment by Swizz** [comment]
hi @adepatie, 

I agree with your point of view.

This repo would not exist without the awesome Bulma, 
I think any kind of greeting for the Bulma's author works (@jgthms) is absolutely essential.

Then, your proposal seems really good.

Do you agree with me @crodriguez1a ?

**Comment by crodriguez1a** [comment]
@adepatie @swizz Funny, someone mentioned to me this week that the wording was confusing. This is a result of my poor grammar. Please feel free to submit a MR. I believe this sentence lives in three places. The package.json, in the dummy app, and on the read me. Thanks!

**Comment by crodriguez1a** [comment]
@adepatie Also, let's submit an MR for GitHub to add a 'very serious' label for issues.

**Comment by Swizz** [comment]
I made your wish come true

**Comment by crodriguez1a** [comment]
@swizz 👍🏽

**Comment by Swizz** [comment]
_off-topic :_ @crodriguez1a Create your own labels on [open-tux/ember-bulma/labels](https://github.com/open-tux/ember-bulma/labels)

**Comment by crodriguez1a** [comment]
@swizz ha...thanks!

**Comment by adepatie** [comment]
@crodriguez1a I'll make an MR with the last, more descriptive, description. 

And haha yes! Every repo needs: 'Very Serious', 'I give up', and 'Free Cake!' tags.
