### ISSUE TITLE
Consider defaulting to button tag on bulma button

### ISSUE THREAD

**Issue by crodriguez1a** [open-tux/ember-bulma#34]

**Comment by crodriguez1a** [comment]
Its seems that the `a` tag is more appropriate since Firefox does not support flex properties on a button elem.

As per @jbailey4 
Looks like flex properties do not work on button elements in firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=984869

**Comment by jbailey4** [comment]
@crodriguez1a Yeah, consumers can always override as needed:

```es6
import BulmaButton from 'ember-bulma/components/bulma-button';

export BulmaButton.extend({
  tagName: 'button',
  ...
});
```
