### ISSUE TITLE
Upgrade to latest bulma

### ISSUE THREAD

**Issue by jonblack** [open-tux/ember-bulma#45]
This addon installs bulma 0.1.2 which was released in July. Since then three releases have been made, the latest being 0.2.3. I'm not sure if there are significant differences, but an issue won't hurt, right? :smile:

**Comment by crodriguez1a** [comment]
@jonblack There are some differences that could potentially break some existing components. I think the strategy we want take is to upgrade gradually (hopefully adding a few new Bulma components along the way). We want to make sure that with each release, we have the time to address any breakage with legacy support or at least deprecation documentation.

cc/ @alexdiliberto @jbailey4

**Comment by alexdiliberto** [comment]
@crodriguez1a is correct here, I'm going to close this issue for now as our current strategy calls for a more deliberate process. As we upgate the component library, we'll see where we can version bump base bulma as needed.
