### ISSUE TITLE
Tab routes not working on documentation site

### ISSUE THREAD

**Issue by adepatie** [open-tux/ember-bulma#5]
Clicking a tab and refreshing the [page](http://open-tux.github.io/ember-bulma/uicomponents) returns a 404.

**Comment by alexdiliberto** [comment]
Should just need to set a hash URL instead of absolute if github pages doesn't have "catch-all" route server logic for nested routes past the base URL for the single page app

```js
  if (environment === 'production') {
    ENV.locationType = 'hash';
  }
```

ping @crodriguez1a
