### ISSUE TITLE
Avoid theming system to Bulma one

### ISSUE THREAD

**Issue by Swizz** [open-tux/ember-bulma#6]
Hi there,

Since 0.0.23 (pushed 13 hours ago), Bulma has self-implemented the sass theming system.

According to [this documentation part.](http://bulma.io/documentation/overview/variables/)

It could be a great thing to update the bulma dependancy to 0.0.23 and update theming part of Ember-Bulma.

Sorry for my bad english, and have a nice day.

Regards,

**Comment by Swizz** [comment]
I just realized. This addon is not used with its sass import capabilities.

What about moving it to sass ?
I can submit it in a pull request.

**Comment by crodriguez1a** [comment]
@Swizz Absolutely, please do! When we began writing the addon, Bulma was decidedly committed to using Less, so we imported the compiled CSS and provided some thin theming. Sass would be a welcome addition to the addon.

**Comment by Swizz** [comment]
I think you could also no longer use the font awesome bower dependancies for moving to [martndemus/ember-font-awesome](https://github.com/martndemus/ember-font-awesome).

We can move it to `optionalDependencies` too.


nb : Should I create a genuine issue for discussing about the SASS rewriting ?

**Comment by crodriguez1a** [comment]
@swizz That'd be great. 👍🏽

**Comment by Swizz** [comment]
duplicate #8
