### ISSUE TITLE
SASS rewriting

### ISSUE THREAD

**Issue by crodriguez1a** [open-tux/ember-bulma#8]
- Moving to sass import for extensibility and proper theming

**Comment by Swizz** [comment]
- [ ] Use SASS import instead of vendor CSS
- [ ] Move Font-Awesome to optional dependencies
- [ ] Update documentations

That's all we need?

**Comment by crodriguez1a** [comment]
@swizz yep

**Comment by Swizz** [comment]
Due to the version update of Bulma. Some components change.

- [ ] Move Menu to Panel
- [ ] Implement Menu
