### ISSUE TITLE
toast notifications?

### ISSUE THREAD

**Issue by NullVoxPopuli** [open-tux/ember-bulma#86]
is there a way to do toast notifications?

like what toastr offers?

**Comment by crodriguez1a** [comment]
@NullVoxPopuli There's an addon called `ember-toastr` that might be helpful to you.

**Comment by NullVoxPopuli** [comment]
that's a good library, but unfortunately, it uses jquery: https://github.com/CodeSeven/toastr/blob/master/package.json#L38

I'm doing an PWA, so I'm trying to be extra careful about how many dependencies I have -- and I know for a fact that jQuery isn't needed now-a-days.

**Comment by crodriguez1a** [comment]
@NullVoxPopuli Gotcha. I'm sure there's an addon out there that would meet your needs. Bulma itself has a notification class and `ember-bulma` has a corresponding component. We typically have kept our components dumb so that users can compose with them as desired.
